version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    labels:
      - "build"
      - "deps"
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps)"
      include: "scope"
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "UTC"
    labels:
      - "build"
      - "deps"
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps)"
      include: "scope"
    groups:
      docker-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
