repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        types_or: [c, c++]
        args: ["-style=file", "-i"]
